export const ROHAN_DATA = {
  about: {
    title: 'About Me',
    intro: 'I am a passionate full-stack developer with a strong foundation in AI/ML, currently pursuing a B.Tech in Computer Engineering.',
    bio: [
      'With 1.5+ years of hands-on experience across internships, open-source contributions, and leadership roles, I have developed a deep expertise in building scalable software solutions.',
      'My journey began with a focus on machine learning and data analytics, but I have evolved into a full-stack engineer capable of architecting complete systems from backend microservices to responsive frontends.',
      'I am driven by the opportunity to create meaningful impact through technology, whether it is improving civic transparency, advancing healthcare through AI, or building tools that empower developers.',
    ],
    highlights: [
      { label: 'Role', value: 'Full-Stack Developer & AI Enthusiast' },
      { label: 'Location', value: 'Satara, Maharashtra, India' },
      { label: 'Education', value: 'B.Tech Computer Engineering (2023-2027)' },
      { label: 'Certifications', value: 'Oracle Cloud AI Associate, ISC2 Candidate' },
    ],
  },

  projects: [
    {
      id: 1,
      title: 'Vishwaguru',
      subtitle: 'AI-Powered Public Grievance Platform',
      description: 'An intelligent civic tech solution that automatically routes citizen complaints to the correct government authorities using geolocation and AI classification.',
      fullDescription: 'Vishwaguru is a groundbreaking social-impact project focused on addressing inefficiencies in public grievance reporting. The platform uses AI to categorize complaints and geolocation APIs to route them to the appropriate authority, reducing resolution time and improving governance transparency.',
      technologies: ['Python', 'REST APIs', 'Geolocation', 'Docker', 'AI Classification'],
      github: 'https://github.com/RohanExploit/Vishwaguru',
      features: [
        'Automatic complaint categorization using ML',
        'Geolocation-based authority routing',
        'Real-time tracking and status updates',
        'Scalable microservices architecture',
        'Docker containerization for deployment',
      ],
      impact: 'Social-impact project aimed at improving civic transparency and government efficiency',
    },
    {
      id: 2,
      title: 'BaliRaja',
      subtitle: 'Farmer\'s Agricultural Recommendation System',
      description: 'A machine learning model that predicts the most suitable crop based on agro-climatic parameters including soil composition, temperature, humidity, and rainfall.',
      fullDescription: 'BaliRaja is designed to help Indian farmers make data-driven decisions about crop selection. The model analyzes 22 common crop types and recommends the best option based on environmental conditions.',
      technologies: ['Python', 'Scikit-Learn', 'Pandas', 'Data Preprocessing', 'Classification'],
      github: 'https://github.com/RohanExploit/BaliRaja-Hackathon',
      features: [
        'Analyzes 22 major Indian crop types',
        'Uses supervised learning classification',
        'Accepts agro-climatic parameters (N, P, K, pH, temperature, humidity, rainfall)',
        'Provides instant crop recommendations',
        'Modular architecture for IoT integration',
      ],
      impact: 'Helps Indian farmers optimize crop selection for better yields',
    },
    {
      id: 3,
      title: 'Heart Disease Prediction',
      subtitle: 'Cardiac Risk ML Pipeline',
      description: 'An end-to-end machine learning pipeline that predicts cardiac risk from clinical parameters using advanced data preprocessing and classification techniques.',
      fullDescription: 'This project demonstrates proficiency in the complete ML workflow: data collection, preprocessing, feature engineering, model training, and evaluation.',
      technologies: ['Python', 'Scikit-Learn', 'Pandas', 'Data Analysis', 'Medical Data'],
      github: 'https://github.com/RohanExploit/Heart_diseases',
      features: [
        'Comprehensive data preprocessing',
        'Feature engineering and selection',
        'Multiple model evaluation',
        'Accuracy and precision metrics',
        'Medical data handling',
      ],
      impact: 'Demonstrates ML pipeline expertise with healthcare applications',
    },
    {
      id: 4,
      title: 'Mushroom Classification Web-App',
      subtitle: 'Image-Based Fungal Classification',
      description: 'An end-to-end machine learning application that classifies mushrooms as poisonous or edible based on 12 major morphological features.',
      fullDescription: 'Built using CNNs and modern ML techniques, this web app demonstrates proficiency in both backend ML and frontend integration.',
      technologies: ['Python', 'TensorFlow', 'CNN', 'React', 'Web Application'],
      github: 'https://github.com/RohanExploit',
      features: [
        'Feature-based classification system',
        'Supervised learning with CNNs',
        'Web-based interface',
        'Real-time predictions',
        'High accuracy classification',
      ],
      impact: 'Demonstrates practical application of deep learning for user-facing systems',
    },
    {
      id: 5,
      title: 'Amazon Data Analytics',
      subtitle: 'E-Commerce Business Intelligence',
      description: 'A comprehensive exploratory data analysis project on Amazon sales data to derive actionable business insights.',
      fullDescription: 'This project showcases data analytics capabilities including trend analysis, pattern recognition, and business insights generation.',
      technologies: ['Python', 'Pandas', 'Plotly', 'Data Visualization', 'SQL'],
      github: 'https://github.com/RohanExploit/amazon_data_analytics',
      features: [
        'Month-wise and year-wise sales trends',
        'Revenue growth analysis',
        'Interactive dashboards with Plotly',
        'Pattern identification',
        'Business recommendations',
      ],
      impact: 'Demonstrates ability to extract valuable insights from large datasets',
    },
  ],

  experience: [
    {
      id: 1,
      title: 'Project Administrator & Technical Mentor',
      company: 'Elite Coders',
      period: 'Jan 2026 - Present',
      type: 'Leadership',
      description: [
        'Architect and design modular system architecture for open-source projects',
        'Manage repository structure, configuration, and issue triage with priority labels',
        'Review pull requests for code quality, logic, and efficiency',
        'Enforce coding standards, linting, and automated CI/CD validation',
        'Guide junior developers through implementation strategies and code refactoring',
        'Oversee release management, versioning, and comprehensive documentation',
      ],
      skills: ['System Architecture', 'Git Workflows', 'Code Review', 'Team Leadership', 'CI/CD'],
    },
    {
      id: 2,
      title: 'Career Counselor',
      company: 'Wadhwani Foundation',
      period: 'Sep 2025 - Present',
      type: 'Mentorship',
      description: [
        'Analyze LMS engagement data and monitor API logs for learning metrics',
        'Generate KPI dashboards and comprehensive analytics reports',
        'Deploy AI-based assessment tools and validate digital module integrations',
        'Automate analytics workflows using Python and Google Sheets',
        'Optimize digital learning pipelines for improved student outcomes',
      ],
      skills: ['Data Analysis', 'Python', 'Dashboard Creation', 'AI Tools', 'Automation'],
    },
    {
      id: 3,
      title: 'AI/ML Intern',
      company: 'Destiny Solutions',
      period: 'Jun 2025 - Oct 2025',
      type: 'Internship',
      description: [
        'Conducted research and development on AI models for disease prediction and diagnosis',
        'Collaborated with backend and product teams to integrate AI into functional systems',
        'Worked with health-related datasets to improve model accuracy',
        'Participated in sprint reviews and weekly progress synchronization',
      ],
      skills: ['Machine Learning', 'AI Research', 'Data Handling', 'Team Collaboration', 'Model Development'],
    },
    {
      id: 4,
      title: 'Full Stack Developer',
      company: 'Y-SoC',
      period: 'Oct 2025 - Dec 2025',
      type: 'Project-Based',
      description: [
        'Debugged and fixed application issues affecting user experience',
        'Improved Lighthouse performance metrics through optimization',
        'Implemented RLS (Row-Level Security) policies in Supabase',
        'Enhanced platform with mentor management features',
      ],
      skills: ['Full Stack Development', 'React', 'Supabase', 'Performance Optimization', 'Security'],
    },
    {
      id: 5,
      title: 'Open Source Contributor',
      company: 'GSSoC & ECWoC',
      period: 'Jul 2025 - Jan 2026',
      type: 'Open Source',
      description: [
        'Architected high-throughput microservices with optimized REST APIs',
        'Refactored monolithic modules into scalable, clean architecture components',
        'Implemented state-driven UI components in React with TypeScript and Redux',
        'Enhanced CI/CD pipelines using GitHub Actions with automated testing',
        'Applied containerization (Docker) for reproducible builds',
        'Authored comprehensive developer documentation and API specifications',
      ],
      skills: ['Microservices', 'React', 'TypeScript', 'Docker', 'GitHub Actions', 'System Design'],
    },
    {
      id: 6,
      title: 'Data Analyst',
      company: 'iNeuron.ai',
      period: 'Nov 2024 - Feb 2025',
      type: 'Internship',
      description: [
        'Performed ETL (Extract-Transform-Load) operations on large datasets',
        'Analyzed sales trends to identify key business insights',
        'Built interactive dashboards for business intelligence',
        'Provided data-driven recommendations for operational efficiency',
      ],
      skills: ['Data Analysis', 'ETL', 'BI Dashboards', 'SQL', 'Python'],
    },
  ],

  skills: {
    technical: [
      {
        category: 'Languages',
        items: ['Python', 'JavaScript', 'TypeScript', 'SQL', 'HTML/CSS'],
      },
      {
        category: 'Frontend',
        items: ['React.js', 'Next.js', 'Tailwind CSS', 'Redux', 'UI/UX'],
      },
      {
        category: 'Backend',
        items: ['Node.js', 'REST APIs', 'Microservices', 'Docker', 'Supabase'],
      },
      {
        category: 'AI/ML',
        items: ['Machine Learning', 'Deep Learning', 'TensorFlow', 'Scikit-Learn', 'Pandas'],
      },
      {
        category: 'DevOps & Tools',
        items: ['Docker', 'GitHub Actions', 'Git', 'CI/CD', 'AWS'],
      },
      {
        category: 'Database',
        items: ['PostgreSQL', 'MongoDB', 'Supabase', 'Data Modeling', 'Query Optimization'],
      },
    ],
    soft: [
      'Problem Solving',
      'Team Leadership',
      'Mentorship',
      'Communication',
      'Project Management',
      'Agile Methodologies',
      'System Design',
      'Code Review',
    ],
  },

  achievements: [
    {
      id: 1,
      title: 'Oracle Cloud Infrastructure AI Foundations Associate',
      issuer: 'Oracle',
      date: 'Jul 2025',
      description: 'Certified in Oracle Cloud AI fundamentals and architecture',
      type: 'Certification',
    },
    {
      id: 2,
      title: 'Accenture - Data Analytics and Visualization',
      issuer: 'Accenture',
      date: 'May 2025',
      description: 'Professional certification in data analytics and visualization techniques',
      type: 'Certification',
    },
    {
      id: 3,
      title: 'ISC2 Cyber Security Candidate',
      issuer: 'ISC2',
      date: 'Jul 2025',
      description: 'Pursuing cybersecurity expertise and industry recognition',
      type: 'Certification',
    },
    {
      id: 4,
      title: 'Google Student Ambassador',
      issuer: 'Google',
      date: 'Aug 2025 - Present',
      description: 'Ambassador promoting Google technologies and conducting trials/demos',
      type: 'Program',
    },
    {
      id: 5,
      title: 'GSSoC 25 Contributor',
      issuer: 'GirlScript Summer of Code',
      date: 'Jul 2025 - Jan 2026',
      description: 'Active open-source contributor during GSSoC program',
      type: 'Program',
    },
    {
      id: 6,
      title: 'ECWoC 25 - Project Admin',
      issuer: 'Elite Coders Winter of Code',
      date: 'Jan 2026 - Present',
      description: 'Project administrator and mentor for open-source initiatives',
      type: 'Program',
    },
    {
      id: 7,
      title: 'BCG Generative AI Internship',
      issuer: 'Boston Consulting Group',
      date: 'Aug 2024',
      description: 'Professional development in generative AI applications and strategy',
      type: 'Certification',
    },
    {
      id: 8,
      title: 'JPMorgan Chase - CADP Program',
      issuer: 'JPMorgan Chase & Co.',
      date: 'Sep 2024',
      description: 'Corporate Analyst Development Program certification',
      type: 'Program',
    },
  ],

  testimonials: [
    {
      id: 1,
      quote: 'Rohan demonstrates exceptional technical depth combined with the ability to mentor junior developers effectively.',
      author: 'Elite Coders Leadership Team',
      role: 'Project Supervisors',
    },
    {
      id: 2,
      quote: 'His contributions to open-source projects show a mature understanding of system design and code quality.',
      author: 'GSSoC Community',
      role: 'Community Recognition',
    },
  ],

  openSourceContributions: [
    {
      id: 1,
      name: 'GSSoC 25 & ECWoC 25',
      description: 'Active contributor in global open-source programs with focus on system architecture and code quality',
      contributions: [
        'Architected microservices with optimized REST APIs',
        'Refactored monolithic modules into scalable components',
        'Implemented state-driven React components with TypeScript',
        'Enhanced CI/CD pipelines with GitHub Actions',
        'Authored comprehensive API documentation',
      ],
      technologies: ['React', 'TypeScript', 'Docker', 'GitHub Actions', 'Node.js'],
      link: 'https://github.com/RohanExploit',
    },
    {
      id: 2,
      name: 'Elite Coders Winter of Code',
      description: 'Project Administrator managing repository architecture and developer guidance',
      contributions: [
        'Designed modular system architecture',
        'Managed GitHub workflows and CI/CD pipelines',
        'Reviewed and merged 50+ pull requests',
        'Mentored 20+ junior developers',
        'Established coding standards and best practices',
      ],
      technologies: ['Git', 'System Design', 'Code Review', 'Leadership', 'DevOps'],
      link: 'https://github.com/RohanExploit',
    },
    {
      id: 3,
      name: 'Community Contributions',
      description: 'Technical contributions and mentorship across multiple platforms',
      contributions: [
        'Multiple merged pull requests across open-source projects',
        'Active GitHub contributor with consistent commit history',
        'Technical mentorship for junior developers',
        'Bug fixes and feature implementations',
        'Documentation improvements',
      ],
      technologies: ['Python', 'JavaScript', 'System Design', 'Documentation', 'Testing'],
      link: 'https://github.com/RohanExploit',
    },
  ],

  contact: {
    email: 'itzrohan007@gmail.com',
    location: 'Satara, Maharashtra, India',
    social: [
      { platform: 'GitHub', url: 'https://github.com/RohanExploit', icon: 'Github' },
      { platform: 'LinkedIn', url: 'https://linkedin.com/in/rohanvijaygaikwad', icon: 'Linkedin' },
      { platform: 'Twitter', url: 'https://x.com/rohan_critic', icon: 'Twitter' },
    ],
    resume: 'https://drive.google.com/file/d/1alaSYAR5b2zUzTa0ZMlaSnZY-RDQ68Og/view?usp=sharing',
  },
}
