export const ROHAN_DATA = {
  about: {
    title: 'About Me',
    intro: 'Software Engineer specializing in scalable intelligence and distributed systems.',
    bio: [
      'I architect and build high-performance software solutions, bridging the gap between advanced machine learning research and production-grade engineering.',
      'With a strong foundation in full-stack development and algorithmic optimization, I have led technical initiatives across internships and open-source communities, delivering robust systems that solve complex real-world problems.',
      'My engineering philosophy centers on writing clean, maintainable code and designing systems that are secure, scalable, and intuitive by default.',
    ],
    highlights: [
      { label: 'Role', value: 'Software Engineer & System Architect' },
      { label: 'Location', value: 'Satara, Maharashtra, India' },
      { label: 'Focus', value: 'Scalable Systems, AI/ML, Cloud Architecture' },
      { label: 'Status', value: 'Open for Engineering Roles' },
    ],
  },

  projects: [
    {
      id: 1,
      title: 'Vishwaguru',
      subtitle: 'AI-Powered Public Grievance Platform',
      description: 'An intelligent civic tech solution that automatically routes citizen complaints to the correct government authorities using geolocation and AI classification.',
      fullDescription: 'Vishwaguru is a groundbreaking social-impact project focused on addressing inefficiencies in public grievance reporting. The platform uses AI to categorize complaints and geolocation APIs to route them to the appropriate authority, reducing resolution time and improving governance transparency.',
      technologies: ['Python', 'REST APIs', 'Geolocation', 'Docker', 'AI Classification'],
      github: 'https://github.com/RohanExploit/Vishwaguru',
      features: [
        'Automatic complaint categorization using ML',
        'Geolocation-based authority routing',
        'Real-time tracking and status updates',
        'Scalable microservices architecture',
        'Docker containerization for deployment',
      ],
      impact: 'Social-impact project aimed at improving civic transparency and government efficiency',
    },
    {
      id: 2,
      title: 'BaliRaja',
      subtitle: 'Farmer\'s Agricultural Recommendation System',
      description: 'A machine learning model that predicts the most suitable crop based on agro-climatic parameters including soil composition, temperature, humidity, and rainfall.',
      fullDescription: 'BaliRaja is designed to help Indian farmers make data-driven decisions about crop selection. The model analyzes 22 common crop types and recommends the best option based on environmental conditions.',
      technologies: ['Python', 'Scikit-Learn', 'Pandas', 'Data Preprocessing', 'Classification'],
      github: 'https://github.com/RohanExploit/BaliRaja-Hackathon',
      features: [
        'Analyzes 22 major Indian crop types',
        'Uses supervised learning classification',
        'Accepts agro-climatic parameters (N, P, K, pH, temperature, humidity, rainfall)',
        'Provides instant crop recommendations',
        'Modular architecture for IoT integration',
      ],
      impact: 'Helps Indian farmers optimize crop selection for better yields',
    },
    {
      id: 3,
      title: 'Heart Disease Prediction',
      subtitle: 'Cardiac Risk ML Pipeline',
      description: 'An end-to-end machine learning pipeline that predicts cardiac risk from clinical parameters using advanced data preprocessing and classification techniques.',
      fullDescription: 'This project demonstrates proficiency in the complete ML workflow: data collection, preprocessing, feature engineering, model training, and evaluation.',
      technologies: ['Python', 'Scikit-Learn', 'Pandas', 'Data Analysis', 'Medical Data'],
      github: 'https://github.com/RohanExploit/Heart_diseases',
      features: [
        'Comprehensive data preprocessing',
        'Feature engineering and selection',
        'Multiple model evaluation',
        'Accuracy and precision metrics',
        'Medical data handling',
      ],
      impact: 'Demonstrates ML pipeline expertise with healthcare applications',
    },
    {
      id: 4,
      title: 'Mushroom Classification Web-App',
      subtitle: 'Image-Based Fungal Classification',
      description: 'An end-to-end machine learning application that classifies mushrooms as poisonous or edible based on 12 major morphological features.',
      fullDescription: 'Built using CNNs and modern ML techniques, this web app demonstrates proficiency in both backend ML and frontend integration.',
      technologies: ['Python', 'TensorFlow', 'CNN', 'React', 'Web Application'],
      github: 'https://github.com/RohanExploit',
      features: [
        'Feature-based classification system',
        'Supervised learning with CNNs',
        'Web-based interface',
        'Real-time predictions',
        'High accuracy classification',
      ],
      impact: 'Demonstrates practical application of deep learning for user-facing systems',
    },
    {
      id: 5,
      title: 'Amazon Data Analytics',
      subtitle: 'E-Commerce Business Intelligence',
      description: 'A comprehensive exploratory data analysis project on Amazon sales data to derive actionable business insights.',
      fullDescription: 'This project showcases data analytics capabilities including trend analysis, pattern recognition, and business insights generation.',
      technologies: ['Python', 'Pandas', 'Plotly', 'Data Visualization', 'SQL'],
      github: 'https://github.com/RohanExploit/amazon_data_analytics',
      features: [
        'Month-wise and year-wise sales trends',
        'Revenue growth analysis',
        'Interactive dashboards with Plotly',
        'Pattern identification',
        'Business recommendations',
      ],
      impact: 'Demonstrates ability to extract valuable insights from large datasets',
    },
    {
      id: 6,
      title: 'Anti-Gravity',
      subtitle: 'Physics-Based UI Interaction System',
      description: 'A frontend-only, physics-inspired UI interaction system that simulates gravity-defying motion using deterministic mathematical models.',
      fullDescription: 'Anti-Gravity is an exploration of how frontend systems can simulate intelligence and physical behavior purely through computation. It features custom motion equations for upward force and inertia, GPU-accelerated rendering for 60 FPS performance, and an event-driven interaction layer that reacts to scroll velocity and cursor movement.',
      technologies: ['React', 'TypeScript', 'Physics Modeling', 'WebGL', 'Vercel'],
      github: 'https://github.com/RohanExploit',
      link: 'https://Rohangaikwad.in',
      features: [
        'Deterministic motion modeling (no presets)',
        'GPU-accelerated rendering pipeline',
        'Event-driven anti-gravity response',
        'Component-level isolation',
        '60 FPS performance optimization',
      ],
      impact: 'Demonstrates ability to design custom animation systems and bridge the gap between visual experience and systems thinking.',
    },
  ],

  experience: [
    {
      id: 1,
      title: 'Project Administrator & Technical Mentor',
      company: 'Elite Coders',
      period: 'Jan 2026 - Present',
      type: 'Leadership',
      description: [
        'Architect and design modular system architecture for open-source projects',
        'Manage repository structure, configuration, and issue triage with priority labels',
        'Review pull requests for code quality, logic, and efficiency',
        'Enforce coding standards, linting, and automated CI/CD validation',
        'Guide junior developers through implementation strategies and code refactoring',
        'Oversee release management, versioning, and comprehensive documentation',
      ],
      skills: ['System Architecture', 'Git Workflows', 'Code Review', 'Team Leadership', 'CI/CD'],
    },
    {
      id: 2,
      title: 'Career Counselor',
      company: 'Wadhwani Foundation',
      period: 'Sep 2025 - Present',
      type: 'Mentorship',
      description: [
        'Analyze LMS engagement data and monitor API logs for learning metrics',
        'Generate KPI dashboards and comprehensive analytics reports',
        'Deploy AI-based assessment tools and validate digital module integrations',
        'Automate analytics workflows using Python and Google Sheets',
        'Optimize digital learning pipelines for improved student outcomes',
      ],
      skills: ['Data Analysis', 'Python', 'Dashboard Creation', 'AI Tools', 'Automation'],
    },
    {
      id: 3,
      title: 'AI/ML Intern',
      company: 'Destiny Solutions',
      period: 'Jun 2025 - Oct 2025',
      type: 'Internship',
      description: [
        'Conducted research and development on AI models for disease prediction and diagnosis',
        'Collaborated with backend and product teams to integrate AI into functional systems',
        'Worked with health-related datasets to improve model accuracy',
        'Participated in sprint reviews and weekly progress synchronization',
      ],
      skills: ['Machine Learning', 'AI Research', 'Data Handling', 'Team Collaboration', 'Model Development'],
    },
    {
      id: 4,
      title: 'Full Stack Developer',
      company: 'Y-SoC',
      period: 'Oct 2025 - Dec 2025',
      type: 'Project-Based',
      description: [
        'Debugged and fixed application issues affecting user experience',
        'Improved Lighthouse performance metrics through optimization',
        'Implemented RLS (Row-Level Security) policies in Supabase',
        'Enhanced platform with mentor management features',
      ],
      skills: ['Full Stack Development', 'React', 'Supabase', 'Performance Optimization', 'Security'],
    },
    {
      id: 5,
      title: 'Open Source Contributor',
      company: 'GSSoC & ECWoC',
      period: 'Jul 2025 - Jan 2026',
      type: 'Open Source',
      description: [
        'Architected high-throughput microservices with optimized REST APIs',
        'Refactored monolithic modules into scalable, clean architecture components',
        'Implemented state-driven UI components in React with TypeScript and Redux',
        'Enhanced CI/CD pipelines using GitHub Actions with automated testing',
        'Applied containerization (Docker) for reproducible builds',
        'Authored comprehensive developer documentation and API specifications',
      ],
      skills: ['Microservices', 'React', 'TypeScript', 'Docker', 'GitHub Actions', 'System Design'],
    },
    {
      id: 6,
      title: 'Data Analyst',
      company: 'iNeuron.ai',
      period: 'Nov 2024 - Feb 2025',
      type: 'Internship',
      description: [
        'Performed ETL (Extract-Transform-Load) operations on large datasets',
        'Analyzed sales trends to identify key business insights',
        'Built interactive dashboards for business intelligence',
        'Provided data-driven recommendations for operational efficiency',
      ],
      skills: ['Data Analysis', 'ETL', 'BI Dashboards', 'SQL', 'Python'],
    },
  ],

  skills: {
    technical: [
      {
        category: 'Languages',
        items: ['Python', 'JavaScript', 'TypeScript', 'SQL', 'HTML/CSS'],
      },
      {
        category: 'Frontend',
        items: ['React.js', 'Next.js', 'Tailwind CSS', 'Redux', 'UI/UX'],
      },
      {
        category: 'Backend',
        items: ['Node.js', 'REST APIs', 'Microservices', 'Docker', 'Supabase'],
      },
      {
        category: 'AI/ML',
        items: ['Machine Learning', 'Deep Learning', 'TensorFlow', 'Scikit-Learn', 'Pandas'],
      },
      {
        category: 'DevOps & Tools',
        items: ['Docker', 'GitHub Actions', 'Git', 'CI/CD', 'AWS'],
      },
      {
        category: 'Database',
        items: ['PostgreSQL', 'MongoDB', 'Supabase', 'Data Modeling', 'Query Optimization'],
      },
    ],
    soft: [
      'Problem Solving',
      'Team Leadership',
      'Mentorship',
      'Communication',
      'Project Management',
      'Agile Methodologies',
      'System Design',
      'Code Review',
    ],
  },

  achievements: [
    {
      id: 1,
      title: 'Oracle Cloud Infrastructure AI Foundations Associate',
      issuer: 'Oracle',
      date: 'Jul 2025',
      description: 'Certified in Oracle Cloud AI fundamentals and architecture',
      type: 'Certification',
    },
    {
      id: 2,
      title: '(Virtual)Accenture - Data Analytics and Visualization',
      issuer: 'Accenture',
      date: 'May 2025',
      description: 'Professional certification in data analytics and visualization techniques',
      type: 'Certification',
    },
    {
      id: 3,
      title: 'ISC2 Cyber Security Candidate',
      issuer: 'ISC2',
      date: 'Jul 2025',
      description: 'Pursuing cybersecurity expertise and industry recognition',
      type: 'Certification',
    },
    {
      id: 4,
      title: 'Google Student Ambassador',
      issuer: 'Google',
      date: 'Aug 2025 - Present',
      description: 'Ambassador promoting Google technologies and conducting trials/demos',
      type: 'Program',
    },
    {
      id: 5,
      title: 'GSSoC 25 Contributor',
      issuer: 'GirlScript Summer of Code',
      date: 'Jul 2025 - Jan 2026',
      description: 'Active open-source contributor during GSSoC program',
      type: 'Program',
    },
    {
      id: 6,
      title: 'ECWoC 25 - Project Admin',
      issuer: 'Elite Coders Winter of Code',
      date: 'Jan 2026 - Present',
      description: 'Project administrator and mentor for open-source initiatives',
      type: 'Program',
    },
    {
      id: 7,
      title: 'BCG Generative AI Internship',
      issuer: 'Boston Consulting Group',
      date: 'Aug 2024',
      description: 'Professional development in generative AI applications and strategy',
      type: 'Certification',
    },
    {
      id: 8,
      title: 'JPMorgan Chase - CADP Program',
      issuer: 'JPMorgan Chase & Co.',
      date: 'Sep 2024',
      description: 'Corporate Analyst Development Program certification',
      type: 'Program',
    },
    {
      id: 9,
      title: 'Google Developer Program Premium Tier',
      issuer: 'Google',
      date: 'Feb 2026',
      description: 'Subscribed member of the Google Developer Program Premium Tier',
      link: 'https://developers.google.com/profile/badges/community/innovators/cloud/innovators_plus',
      type: 'Certification',
    },
    {
      id: 10,
      title: 'Android Studio User',
      issuer: 'Google',
      date: 'Aug 2025',
      description: 'Recognized active user of Android Studio development environment',
      link: 'https://developers.google.com/profile/badges/activity/android/install-android-studio',
      type: 'Certification',
    },
    {
      id: 11,
      title: 'Google Developer Groups (GDG)',
      issuer: 'Google Developer Groups',
      date: 'Member',
      description: 'Community member connecting and collaborating with developers and Googlers globally',
      type: 'Program',
    },
    {
      id: 12,
      title: 'Google Cloud & NVIDIA',
      issuer: 'Google Cloud & NVIDIA',
      date: 'Member',
      description: 'Community for practitioners leveraging NVIDIA and Google Cloud technologies',
      link: 'https://goo.gle/nvidia',
      type: 'Program',
    },
    {
      id: 13,
      title: 'Google Cloud Innovators',
      issuer: 'Google Cloud',
      date: 'Member',
      description: 'Community program providing access to experts and recognition for cloud contributions',
      type: 'Program',
    },
    {
      id: 14,
      title: 'Code Wiki Early Access',
      issuer: 'Google',
      date: 'Waitlist',
      description: 'Early access member for the Gemini CLI extension for Code Wiki',
      type: 'Program',
    },
    {
      id: 15,
      title: 'Firebase Studio Developer',
      issuer: 'Firebase',
      date: 'Member',
      description: 'Community member utilizing Firebase Studio for full-stack and AI-infused apps',
      type: 'Program',
    },
    {
      id: 16,
      title: 'Google Maps Platform Innovators',
      issuer: 'Google Maps Platform',
      date: 'Member',
      description: 'Community program offering technical resources for mapping innovation',
      type: 'Program',
    },
  ],

  testimonials: [
    {
      id: 1,
      quote: 'Rohan demonstrates exceptional technical depth combined with the ability to mentor junior developers effectively.',
      author: 'Elite Coders Leadership Team',
      role: 'Project Supervisors',
    },
    {
      id: 2,
      quote: 'His contributions to open-source projects show a mature understanding of system design and code quality.',
      author: 'GSSoC Community',
      role: 'Community Recognition',
    },
  ],

  openSourceContributions: [
    {
      id: 1,
      name: 'GSSoC 25 & ECWoC 25',
      description: 'Active Project Admin & contributor in global open-source programs with focus on system architecture and code quality',
      contributions: [
        'Architected microservices with optimized REST APIs',
        'Refactored monolithic modules into scalable components',
        'Implemented state-driven React components with TypeScript',
        'Enhanced CI/CD pipelines with GitHub Actions',
        'Authored comprehensive API documentation',
      ],
      technologies: ['React', 'TypeScript', 'Docker', 'GitHub Actions', 'Node.js'],
      link: 'https://github.com/RohanExploit',
    },
    {
      id: 2,
      name: 'Elite Coders Winter of Code',
      image: '/projects/ecwoc.jpg',
      description: 'Project Administrator managing repository architecture, CI/CD pipelines, and developer guidance for large-scale open source initiatives.',
      contributions: [
        'Designed modular system architecture for high-traffic repositories',
        'Managed GitHub workflows and CI/CD pipelines',
        'Reviewed and merged 50+ pull requests',
        'Mentored 20+ junior developers',
        'Established coding standards and best practices',
      ],
      technologies: ['Git', 'System Design', 'Code Review', 'Leadership', 'DevOps'],
      link: 'https://github.com/RohanExploit',
    },
    {
      id: 3,
      name: 'Community Contributions',
      description: 'Technical contributions and mentorship across multiple platforms',
      contributions: [
        'Multiple merged pull requests across open-source projects',
        'Active GitHub contributor with consistent commit history',
        'Technical mentorship for junior developers',
        'Bug fixes and feature implementations',
        'Documentation improvements',
      ],
      technologies: ['Python', 'JavaScript', 'System Design', 'Documentation', 'Testing'],
      link: 'https://github.com/RohanExploit',
    },
  ],

  contact: {
    email: 'itzrohan007@gmail.com',
    phone: '+917057200895',
    location: 'Satara, Maharashtra, India',
    social: [
      { platform: 'GitHub', url: 'https://github.com/RohanExploit', icon: 'Github' },
      { platform: 'LinkedIn', url: 'https://linkedin.com/in/rohanvijaygaikwad', icon: 'Linkedin' },
      { platform: 'Twitter', url: 'https://x.com/rohan_critic', icon: 'Twitter' },
    ],
    resume: 'https://drive.google.com/file/d/1alaSYAR5b2zUzTa0ZMlaSnZY-RDQ68Og/view?usp=sharing',
  },

  profilePhoto: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/profile%20photo-IUkJLFFn1HXs8tLuGH52CML8IR36Pu.jpg',
}
